### ISSUE TITLE
pdd fails on utf-16 file

### ISSUE THREAD

**Issue by dispmaxstaff** [yegor256/pdd#37] opened 2015-03-29 08:42 UTC
Encountered on Visual Studio Resource files (.rc) extension.
Here's the example of such file: https://github.com/dispmaxstaff/yegor256/blob/master/HelloWorld/HelloWorld/HelloWorld.rc

**Comment by yegor256** [comment] 2015-03-29 17:36
@dispmaxstaff definitely a bug, thanks for reporting

**Comment by davvd** [comment] 2015-03-30 21:58
@yegor256 this is yours, pls go ahead

**Comment by davvd** [comment] 2015-03-30 22:01
@dispmaxstaff thanks for the ticket, your account was topped for 15 mins, payment 54545810

**Comment by dispmaxstaff** [comment] 2015-04-24 00:58
We recently had a problem in our secp project. Our secp.rc file was unicode and git treats it as binary. So after binary merge happened, secp.rc had broken unicode and cannot be read by pdd (even it's in ignore list).
```
INFO: "my version is 0.14"
INFO: "reading ."
INFO: "excluding **/*.exe"
INFO: "excluding **/*.dll"
INFO: "excluding **/*.ico"
INFO: "excluding **/*.rc"
INFO: "44 file(s) found"
/var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:43:in `match': invalid byte sequence in UTF-8 (ArgumentError)
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:43:in `block in puzzles'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:42:in `each'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:42:in `each_with_index'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:42:in `puzzles'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd/source.rb:134:in `puzzles'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:96:in `block (3 levels) in xml'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:95:in `each'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:95:in `block (2 levels) in xml'
    from /var/lib/gems/1.9.1/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:391:in `call'
    from /var/lib/gems/1.9.1/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:391:in `insert'
    from /var/lib/gems/1.9.1/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:375:in `method_missing'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:94:in `block in xml'
    from /var/lib/gems/1.9.1/gems/nokogiri-1.6.5/lib/nokogiri/xml/builder.rb:293:in `initialize'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:92:in `new'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/lib/pdd.rb:92:in `xml'
    from /var/lib/gems/1.9.1/gems/pdd-0.14/bin/pdd:90:in `<top (required)>'
    from /usr/local/bin/pdd:23:in `load'
    from /usr/local/bin/pdd:23:in `<main>'
```
@yegor256 the issue here is: 
- *.rc are ignored `INFO: "excluding **/*.rc"`
- I had to resort to `puts` in `pdd/source.rb` to find out what file fails.
- looks like pdd doesn't really skip *.rc without reading
- so when file is broken unicode - pdd will fail

**Comment by yegor256** [comment] 2015-05-04 23:18
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment] 2015-05-04 23:30
@dispmaxstaff I think that the best we can do here is log each file being processed (done in 0.14.1). we can't accept UTF-16 (or any other encodings) in the same repository. all files should be UTF-8. so, I believe, this ticket can be closed now.

**Comment by dispmaxstaff** [comment] 2015-05-15 08:21
@yegor256 ok, closing

**Comment by yegor256** [comment] 2015-05-15 20:50
@dispmaxstaff yes, make sense... let me check again

**Comment by yegor256** [comment] 2015-10-15 18:23
@dispmaxstaff I think the problem is fixed already, please check (if you can) and close the ticket. Thanks!

**Comment by yegor256** [comment] 2017-12-07 14:11
@dispmaxstaff  I'm closing it, the problem is gone, in my opinion. If you see it again, please submit a new ticket. Thanks for using the tool and your contribution!

**Closed by yegor256** 2017-12-07 14:11 UTC
Labels: 30 mins, bug, DEV

**Comment by 0crat** [comment] 2017-12-08 13:29
Oops! Job `gh:yegor256/pdd#37` is not in scope.

**Comment by 0crat** [comment] 2017-12-08 13:38
Oops! There is no order for job `gh:yegor256/pdd#37`.
