### ISSUE TITLE
Allow `TODO:` and `TODO` as PDD tag to better align with C#/F# .NET Codebases

### ISSUE THREAD

**Issue by SilasReinagel** [yegor256/pdd#106] opened 2018-07-01 16:38 UTC
For .NET Developers, they don't use annotations and the convention is to write TODO in all caps, sometimes with a : at the end.

It would be a very useful feature if 0pdd were able to treat those as Puzzle tags and the interpret the remainder of the puzzle to create a ticket.

This was one of the reasons I stopped using 0pdd in some of my .NET projects. It was very inconsistent from the normal code style.

Example: ```// TODO: #16 This needs to use Trigonometry to apply the velocity correctly```

Original ticket: https://github.com/yegor256/0pdd/issues/202

**Comment by 0crat** [comment] 2018-07-01 16:38
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-07-02 11:52
Job [#106](https://github.com/yegor256/pdd/issues/106) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-07-02 11:52
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment] 2018-07-06 06:52
The job [#106](https://github.com/yegor256/pdd/issues/106) assigned to @a6cexz[/z](https://www.0crat.com/u/a6cexz), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1870667026); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by a6cexz** [comment] 2018-07-08 16:35
@0crat wait #107

**Comment by 0crat** [comment] 2018-07-08 16:40
> @0crat wait #109  ([here](https://github.com/yegor256/pdd/issues/106#issuecomment-403299749))

@a6cexz The impediment for [#106](https://github.com/yegor256/pdd/issues/106) was registered successfully by @a6cexz[/z](https://www.0crat.com/u/a6cexz)

**Comment by 0crat** [comment] 2018-07-16 13:45
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @SilasReinagel (its creator); I won't close the order; please, re-open it and ask @SilasReinagel to close it

**Comment by SilasReinagel** [comment] 2018-07-16 14:06
@yegor256 Can you please re-open this ticket, so that@a6cexz can earn his points?

**Comment by yegor256** [comment] 2018-07-16 14:29
@SilasReinagel done

**Comment by 0crat** [comment] 2018-07-16 14:29
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Closed** 2018-07-16 15:36 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2018-07-16 15:51
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac5f120-3284-4029-a28e-e08780c3ba80, thread: AsyncFlush-5
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/pdd#106] declared for identity constraint of element "verbosity".
```

[0.25.15](https://github.com/zerocracy/farm): CID: [1971537906](https://www.0crat.com/C3T46CUJJ/1971537906), Type: "Close job", Author: "silasreinagel"

**Comment by 0crat** [comment] 2018-07-16 15:51
Order was finished: +30 point(s) just awarded to @a6cexz[/z](https://www.0crat.com/u/a6cexz)

**Comment by 0crat** [comment] 2018-07-16 15:51
The job [#106](https://github.com/yegor256/pdd/issues/106) is now out of scope
