### ISSUE TITLE
PDD should fail if "todo" is invalid

### ISSUE THREAD

**Issue by g4s8** [yegor256/pdd#77] opened 2017-10-24 16:12 UTC
I mistyped `todo` comment with witespace after `#` char :
```
@todo # 266:30min some-text...
```
PDD just skipped this comment without error.

**Comment by 0crat** [comment] 2017-10-24 16:13
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment] 2017-10-24 17:15
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment] 2017-10-24 17:46
Job `gh:yegor256/pdd#77` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment] 2017-10-24 17:47
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4320](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment] 2017-10-24 18:15
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment] 2017-10-24 18:45
Oops! Job `gh:yegor256/pdd#77` is already assigned to @yegor256.

**Comment by 0crat** [comment] 2017-11-14 15:01
@yegor256 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment] 2017-11-14 15:14
@yegor256 resigned from `gh:yegor256/pdd#77`, please stop working.

**Comment by 0crat** [comment] 2017-11-14 15:15
Oops! Job `gh:yegor256/pdd#77` is not assigned to anyone.

**Comment by yegor256** [comment] 2017-12-07 14:11
@g4s8 seems to be a duplicate of #34

**Closed by yegor256** 2017-12-07 14:11 UTC

**Comment by 0crat** [comment] 2017-12-08 13:29
Order was successfully finished: +30 points just awarded to @tedtoer, total is [+120](http://www.0crat.com/u/tedtoer).

**Comment by 0crat** [comment] 2017-12-08 13:33
Job `gh:yegor256/pdd#77` is now out of scope.
