### ISSUE TITLE
Garbage characters in a puzzle name with Thymeleaf parser-level comment

### ISSUE THREAD

**Issue by php-coder** [yegor256/pdd#104] opened 2018-06-21 14:26 UTC
For the following comment:
```html
<!--/* @todo #884 /collection/{slug}/estimation: optimize summing of prices */-->
```
@0pdd created the issue with a title `/collection/{slug}/estimation: optimize summing of prices */-->`.

I think that it has happened because pdd incorrectly parses [Thymeleaf parser-level comments](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#thymeleaf-parser-level-comment-blocks).

Expected result: puzzle shouldn't have `*/-->` at the end.

**Comment by 0crat** [comment] 2018-06-21 14:28
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9f6c64e7-3621-4c53-a7db-c4ce7a5cf502, thread: pool-28-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "catalog.xml" in "PMO" in 2min: 57e5019db0b7/9min/0/0/false/false by zerocrat_bot Telegram Executor
```

[0.22.28](https://github.com/zerocracy/farm): Issue: yegor256/pdd#104, Action: `opened`

**Comment by 0crat** [comment] 2018-06-24 08:01
Job [#104](https://github.com/yegor256/pdd/issues/104) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-06-24 08:01
Thanks for your contribution, @php-coder[/z](https://www.0crat.com/u/php-coder)! If you would be a member of [the project](https://www.0crat.com/p/C3T46CUJJ), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment] 2018-07-06 06:42
The job [#104](https://github.com/yegor256/pdd/issues/104) assigned to @a6cexz[/z](https://www.0crat.com/u/a6cexz), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1870656904); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment] 2018-07-11 07:37
@a6cexz[/z](https://www.0crat.com/u/a6cexz) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by a6cexz** [comment] 2018-07-11 19:56
@0crat wait #110

**Comment by 0crat** [comment] 2018-07-11 19:56
> @0crat wait #110 ([here](https://github.com/yegor256/pdd/issues/104#issuecomment-404290998))

@a6cexz The impediment for [#104](https://github.com/yegor256/pdd/issues/104) was registered successfully by @a6cexz[/z](https://www.0crat.com/u/a6cexz)

**Closed** 2018-07-12 05:17 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2018-07-12 05:33
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @php-coder[/z](https://www.0crat.com/u/php-coder) (its creator); I won't close the order; please, re-open it and ask @php-coder[/z](https://www.0crat.com/u/php-coder) to close it

**Comment by a6cexz** [comment] 2018-07-12 07:02
@php-coder please close this issue, #110 pr with the fix was recently merged

**Comment by php-coder** [comment] 2018-07-12 10:37
@a6cexz I can't close it (there is no button for that).

**Comment by a6cexz** [comment] 2018-07-12 17:10
@php-coder I think you need to re-open this issue and them close it

**Comment by php-coder** [comment] 2018-07-12 17:16
@a6cexz I can't reopen it either.

**Comment by a6cexz** [comment] 2018-07-12 20:41
@yegor256 would you please reopen and close this ticket, as it seems only you can do it, would greatly appreciate your help with this.

**Comment by 0crat** [comment] 2018-07-20 09:49
@a6cexz[/z](https://www.0crat.com/u/a6cexz) resigned from [#104](https://github.com/yegor256/pdd/issues/104), since the job is not in scope anymore

**Comment by 0crat** [comment] 2018-07-20 09:49
The job [#104](https://github.com/yegor256/pdd/issues/104) is now out of scope

**Comment by yegor256** [comment] 2018-12-25 13:41
@rultor release, tag is `0.20.4`

**Comment by yegor256** [comment] 2018-12-25 13:54
@rultor release, tag is `0.20.4`
